### ISSUE TITLE
用药助手

### ISSUE THREAD

**Issue by wyek1n** [Alex0510/Eric#4]
感谢大佬默默付出，是否可以尝试帮忙看看能否破解“用药助手”的订阅？

叨扰见谅，再次感谢！

**Comment by wyek1n** [comment]
E大，同步下sgmodule呗，感谢[爱心]

**Comment by Alex0510** [comment]
那个是我共享的VIP，短暂性，没必要改、有需求赶紧下载VIP文档保存，VIP到期就失效了发自我的 iPhone在 2022年10月15日，13:36，wyek1n ***@***.***> 写道：﻿
E大，同步下sgmodule呗，感谢[爱心]

**Comment by wyek1n** [comment]
> 那个是我共享的VIP，短暂性，没必要改、有需求赶紧下载VIP文档保存，VIP到期就失效了发自我的 iPhone在 2022年10月15日，13:36，wyek1n ***@***.***> 写道：﻿ E大，同步下sgmodule呗，感谢[爱心] —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

收到，感谢！～～
