### ISSUE TITLE
脚本适用版本请教

### ISSUE THREAD

**Issue by ligyff** [Alex0510/Eric#7]
infusepro.js适用于哪个版本。 infuse.js要和pro一起使用吗

**Comment by Alex0510** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Alex0510** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
